version: '3'
services:
  server:
    build:
      context: . # This now correctly points to the project root where the Dockerfile is located
      dockerfile: Dockerfile.dev # Updated to reflect the Dockerfile's new location
    ports:
      - "8080:8080"
    volumes:
      - ./server/database.db:/project-root/server/database.db
      - ./server/migrations:/project-root/server/migrations
      - ./server/src:/project-root/server/src