version: '3'
services:
  server:
    build:
      context: . # This now correctly points to the project root where the Dockerfile is located
      dockerfile: Dockerfile.prod # Updated to reflect the Dockerfile's new location

    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SALT=${SALT}
      - AUTH_SECRET=${AUTH_SECRET}
      - RAPID_API_KEY=${RAPID_API_KEY}
      - PEXELS_API_KEY=${PEXELS_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./server/database.db:/project-root/server/database.db
      - ./server/migrations:/project-root/server/migrations
      - ./server/src:/project-root/server/src
      - ./dashboard:/project-root/dashboard 