version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./migrations:/server/migrations
      - ./src:/server/src