services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    # Make sure to deliver correct .env file to container
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./words.db:/words.db
      - ./migrations:/migrations