version: '3'
services:
  server:
    build: 
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./database.db:/server/database.db
      - ./migrations:/server/migrations
      - ./src:/server/src
