services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=words.db
    ports:
      - "8080:8080"
    volumes:
      - ./words.db:/words.db
      - ./migrations:/migrations